= Liau Jian Jie - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Heart²

---

== Overview

Heart² is a desktop wedding management application used for matching service providers to clients. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Automatching
** What it does: Automatically finds service providers that can fulfill the requirements of a client.
** Justification: Manually searching for service providers for clients is extremely labourious and repetitive.
** Highlights: Reduces the workload of matching to a single command.

* *Minor enhancement*: Contact type serialization
** What it does: Serializes the contact (both clients and service providers) as different types of entities.
** Justification: Previously, there was no mechanism to differentiate between clients and service providers when the data is pulled out from the XML database.
** Highlights: Serializes both client and service provider data into the same address book XML database.

* *Code contributed*:

* *Other contributions*:


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
