= Liau Jian Jie - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Heart²

---

== Overview

Heart² is an enterprise wedding management desktop application that allows wedding agencies to easily match clients (couples looking to have a wedding ceremony) to service providers (companies that offer services catered to weddings).

Some features include:

* CLI interface and rich GUI interface
* Client and service provider database
* Detailed tabular breakdown of the services requested by clients and services offered by service providers
* Auto-matching of clients and service providers

This document serves as a summary for my contribution to the Heart² project.

== Summary of contributions

* *Major enhancement*: Automatching
** What it does: Automatically finds service providers that can fulfill the requirements of a client.
** Justification: Manually searching for service providers for clients is extremely labourious and repetitive.
** Highlights: Reduces the workload of matching to a single command.

* *Minor enhancement*: Contact type serialization
** What it does: Serializes the contact (both clients and service providers) as different types of entities.
** Justification: Previously, there was no mechanism to differentiate between clients and service providers when the data is pulled out from the XML database.
** Highlights: Serializes both client and service provider data into the same address book XML database.

* *Code contributed*:

* *Other contributions*:


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
