= Lim Wai Lun - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Heart²

This portfolio aims to document my contributions to the project *_Heart²_*.

GitHub: https://github.com/CS2103-AY1819S1-F10-3/main

== Overview

*_Heart²_* is a desktop wedding application for wedding planners to efficiently manage their clients and vendors.
*_Heart²_* allows wedding planners to quickly find suitable clients and vendors by automatically matching them together based on the vendors' services and the client's requirements.
The user primarily interacts with *_Heart²_* through a CLI, and it has a GUI created with JavaFX.
*_Heart²_* is written in Java, with about 10 kLoC.

== Summary of contributions

=== *Major enhancement*:

Enabled support for two different types of contacts, clients and vendors, in *_Heart²_*.

** What it does:

Allows the user to be work with two different types of contacts using *_Heart²_*.

** Justification:

*_Heart²_* is made for wedding planners to efficiently manage their clients and vendors, two of their key stakeholders.
Therefore, we chose to model the contacts in *_Heart²_* after clients and vendors.

** Highlights

. This enhancement serves a foundation of many features in *_Heart²_*, including:
`add`, `delete`, `update`, `view`, `list`, `addservice` and `automatch`.

. In *_Heart²_*, the users are presented with two separated lists.
However, in *_Heart²_*, there is only one contact list for both clients and vendors.
Filters are constantly applied to this contact list as commands are entered so as to maintain the illusion of a distinct list to the user.

. This enhancement required extensive refactoring of the codebase as the inherited, legacy code only supported a single contact.
*_Heart²_* currently supports two types of contacts, and can easily be extended to support even more types of contacts with this enhancement.

=== *Major enhancement*:

Implemented unique IDs for contacts.

** What it does:

Allows the user to refer to contacts by their unique IDs.

** Justification:

The inherited implementation from AddressBook (Level 4) had users use the contact's relative position in the currently shown list to refer to that contact.
For our users to make use of their time most efficiently, we chose to have our users be able to refer to contacts using IDs, as opposed to the previous implementation.

In the previous, inherited implementation from AddressBook (Level 4), the user must ensure that the current list shown in the UI contains the contact *and* check the contact's relative position on the list.
With unique IDs for contacts, the context of the commands do not change, and this allows our users to know quickly the context of their commands and thus execute any command at any point of time in *_Heart²_*.

With this unique ID system, our users are able to simplify and improve their workflow on *_Heart²_*,

** Highlights:

. This enhancement serves as another foundation of many features in *_Heart²_*, including:
`delete`, `update`, `view`, `addservice` and `automatch`.

. Together with the contact type, it allows *_Heart²_* to be able to offer a very simple and intuitive command syntax.
Commands pertaining to a contact type start with the contact type (`client` or `vendor`).
In addition, commands pertaining to a specific contact have the unique ID appended to the contact type.

=== *Minor enhancement*:

Updated the main parser that parses all commands entered by the user.

** What it does:

Implements the command syntax enabled by the two previously mentioned enhancements.

** Highlights:

. This enhancement although minor proved to be quite a challenge, because commands differ in their components.
+
For example, `help` consists of just a word, `client list` consists of two words, `vendor#3 delete` consists of 2 words and the unique ID, and lastly `client#1 update n/Wai Lun` consists of 2 words, the unique ID and the parameters for the command.
+
It required some research on regular expressions in Java and tinkering in JShell.
In the end, only a single parser is used to parse and identify all of *_Heart²_* commands when they are entered by the user.


=== *Minor enhancement*:

Extended the `add`, `delete`, `update` and `view` commands in *_Heart²_*.

** What it does:

Gives functionality to the mentioned commands.

** Highlights:

. This enhancement makes use of and relies on all three enhancements mentioned above.

. The text feedback to the user is customised based on the command entered by the user.
+
Due to having two possibilities (`client` and `vendor`) for these commands, and in order avoid "hard-coding" every possible text feedback to the user, these text feedback use Java's string formatting feature.
+
This also means that these text feedback can be easily extended if we choose to add more contact types in the future.


=== *Code contributed*:

The following pull requests are some examples of my code contribution, both functional and test code, to the *_Heart²_* project.

. https://github.com/CS2103-AY1819S1-F10-3/main/pull/83[[Support for different types of contacts]]
. https://github.com/CS2103-AY1819S1-F10-3/main/pull/161[[Implementing the unique ID feature]]
. https://github.com/CS2103-AY1819S1-F10-3/main/pull/193[[Displaying the correct text feedback to the user]]


. https://github.com/CS2103-AY1819S1-F10-3/main/pull/300[[Adding tests for uncovered lines]]
. https://github.com/CS2103-AY1819S1-F10-3/main/pull/303[[Finding and fixing bugs, and adding test cases to cover them]]


=== *Other contributions*:

. Helped solve bug fixes in *_Heart²_*.

. Participated actively in discussions regarding *_Heart²_* and its features.

. As of 11 November 2018:
.. Contributed 39 link:https://github.com/CS2103-AY1819S1-F10-3/main/pulls?utf8=✓&q=is%3Apr+author%3Awailunlim+is%3Aclosed[pull requests] on Github.
.. Reviewed 21 link:https://github.com/CS2103-AY1819S1-F10-3/main/pulls?utf8=✓&q=is%3Apr+reviewed-by%3Awailunlim+[pull requests] on Github.
.. Raised 21 link:https://github.com/CS2103-AY1819S1-F10-3/main/issues?utf8=✓&q=is%3Aclosed+is%3Aissue+author%3Awailunlim+[issues] on Github.

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
