= Lim Wai Lun - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Heart²

This portfolio aims to document my contributions to the project *_Heart²_*.

GitHub: https://github.com/CS2103-AY1819S1-F10-3/main

== Overview

*_Heart²_* is a desktop wedding application for wedding planners to efficiently manage their clients and vendors.
*_Heart²_* allows wedding planners to quickly find suitable clients and vendors by automatically matching them together based on the vendors' services and the client's requirements.
The user primarily interacts with *_Heart²_* through a CLI, and it has a GUI created with JavaFX.
*_Heart²_* is written in Java, with about 10 kLoC.

== Summary of contributions

* *Major enhancement*:

Enabled support for two different types of contacts, clients and vendors, in *_Heart²_*.

** What it does:

Allows the user to be work with two different types of contacts using *_Heart²_*.

** Justification:

*_Heart²_* is made for wedding planners to efficiently manage their clients and vendors, two of their key stakeholders.
Therefore, we chose to model the contacts in *_Heart²_* after clients and vendors.

** Highlights

. This enhancement serves as the foundation our many of the features in *_Heart²_*, including:
`add`, `delete`, `update`, `view`, `list`, `addservice` and `automatch`.

. In *_Heart²_*, the users are presented with two separated lists.
However, in *_Heart²_*, there is only one contact list for both clients and vendors.
Filters are constantly applied to this contact list as commands are entered so as to maintain the illusion of a distinct list to the user.

. This enhancement required extensive refactoring of the codebase as the inherited, legacy code only supported a single contact.
*_Heart²_* currently supports two types of contacts, and can easily be extended to support even more types of contacts with this enhancement.

* *Major enhancement*:

Implemented unique IDs for contacts.

** What it does:


~~~~~~~~~~~~~~~

* *Major enhancement*:

Extended the `add`, `delete`, `update` and `select` commands of Heart².

** What it does:

Augments Heart² to support two different types of contacts, namely `client` and `vendor`.

** Justification:

We identified that the key stakeholders of wedding planners are their clients and vendors.
As such, Heart² had to be able to

* *Major enhancement*:

Updated the command parser of Heart².

** What it does:

Gives the users of Heart² a command syntax that is intuitive to use.

** Justification:

Heart², being a Wedding Management System, supports two different types of contacts, namely `client` and `vendor`.
However, we also noted that such added functionality might inadvertently add complexity to Heart².
Keeping our users in mind, we thus sought to redesign our command syntax to make it intuitive to the user.

** Highlights:

Heart² features an intuitive command syntax for our users' benefit. Users can follow a simple rule summarised below:

_Commands pertaining to contacts start with `client` and `vendor` respectively.
To specify a particular `client` or `vendor`, simply append the unique ID of the contact at the back._

Examples:

`vendor list`

`client add n/Bob e/bob@example.com p/999 a/Bobby Street`

`vendor#3 update p/987`

`client#5 delete`


* *Major enhancement*:

Extended the `add`, `delete, `update` and `select` commands of Heart².

** What it does:

Allows users to use these commands...

** Justification:

As a Wedding Management System, we identified that our key stakeholders are the clients and the vendors.
We chose to...

** Highlights:

highlights here

* *Minor enhancement*:

* *Code contributed*:

* *Other contributions*:


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
